PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTWFM_HCM_SUBTYP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTWFM_HCM_SUBTYP-INFOTYPE .
    FIELD ZTWFM_HCM_SUBTYP-SUBTYPE .
    FIELD ZTWFM_HCM_SUBTYP-DESCRIPTION .
    FIELD ZTWFM_HCM_SUBTYP-CONTINGENT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTWFM_HCM_SUBTYP-INFOTYPE .
    FIELD ZTWFM_HCM_SUBTYP-SUBTYPE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
