*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZHR_EMAIL_RECBTOP.                " Global Data
  INCLUDE LZHR_EMAIL_RECBUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZHR_EMAIL_RECBF00                      . " subprograms
  INCLUDE LZHR_EMAIL_RECBI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZHR_EMAIL_RECBF...                " Subprograms
* INCLUDE LZHR_EMAIL_RECBO...                " PBO-Modules
* INCLUDE LZHR_EMAIL_RECBI...                " PAI-Modules
