PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZHR_RECIBO_LOG CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZHR_RECIBO_LOG-PERNR .
    FIELD ZHR_RECIBO_LOG-MES .
    FIELD ZHR_RECIBO_LOG-ANO .
    FIELD ZHR_RECIBO_LOG-ENTRY_DATE .
    FIELD ZHR_RECIBO_LOG-ENTRY_TIME .
    FIELD ZHR_RECIBO_LOG-SPOOLID .
    FIELD ZHR_RECIBO_LOG-OBJECTID .
    FIELD ZHR_RECIBO_LOG-ESTADO .
    FIELD ZHR_RECIBO_LOG-SEND .
    FIELD ZHR_RECIBO_LOG-USERID .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZHR_RECIBO_LOG-PERNR .
    FIELD ZHR_RECIBO_LOG-MES .
    FIELD ZHR_RECIBO_LOG-ANO .
    FIELD ZHR_RECIBO_LOG-ENTRY_DATE .
    FIELD ZHR_RECIBO_LOG-ENTRY_TIME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
