*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZHR_RECIBO_LOGTOP.                " Global Data
  INCLUDE LZHR_RECIBO_LOGUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZHR_RECIBO_LOGF00                      . " subprograms
  INCLUDE LZHR_RECIBO_LOGI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZHR_RECIBO_LOGF...                " Subprograms
* INCLUDE LZHR_RECIBO_LOGO...                " PBO-Modules
* INCLUDE LZHR_RECIBO_LOGI...                " PAI-Modules
