PROCESS BEFORE OUTPUT.
 MODULE STATUS_0300.
 MODULE init_0300.

PROCESS AFTER INPUT.

 MODULE exit_download_pdf AT EXIT-COMMAND.
 MODULE USER_COMMAND_0300.

PROCESS ON VALUE-REQUEST.
  FIELD gv_dir MODULE search_dir.
