*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZHR_DIR_BUKRSTOP.                 " Global Data
  INCLUDE LZHR_DIR_BUKRSUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZHR_DIR_BUKRSF00                       . " subprograms
  INCLUDE LZHR_DIR_BUKRSI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZHR_DIR_BUKRSF...                 " Subprograms
* INCLUDE LZHR_DIR_BUKRSO...                 " PBO-Modules
* INCLUDE LZHR_DIR_BUKRSI...                 " PAI-Modules
