*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZHRDIUTURNIDADESTOP.              " Global Data
  INCLUDE LZHRDIUTURNIDADESUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZHRDIUTURNIDADESF00                    . " subprograms
  INCLUDE LZHRDIUTURNIDADESI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZHRDIUTURNIDADESF...              " Subprograms
* INCLUDE LZHRDIUTURNIDADESO...              " PBO-Modules
* INCLUDE LZHRDIUTURNIDADESI...              " PAI-Modules
