CLEAR: V_TIPO_REND.
CASE W_OUTPUT2-INC_TYPE(1).
  WHEN 'A'.
    CONCATENATE W_OUTPUT2-INC_TYPE '- TRABALHO DEPENDENTE'
    INTO V_TIPO_REND SEPARATED BY SPACE.
  WHEN 'B'.
    CONCATENATE W_OUTPUT2-INC_TYPE '- TRABALHO INDEPENDENTE'
    INTO V_TIPO_REND SEPARATED BY SPACE.

      WHEN 'C'.
    CONCATENATE W_OUTPUT2-INC_TYPE '- CAPITAIS'
    INTO V_TIPO_REND SEPARATED BY SPACE.

      WHEN 'F'.
    CONCATENATE W_OUTPUT2-INC_TYPE '- PREDIAS'
    INTO V_TIPO_REND SEPARATED BY SPACE.

      WHEN 'G'.
    CONCATENATE W_OUTPUT2-INC_TYPE '- INCREMENTOS PATRIMONIAIS'
    INTO V_TIPO_REND SEPARATED BY SPACE.

      WHEN 'H'.
    CONCATENATE W_OUTPUT2-INC_TYPE '- PENSÕES'
    INTO V_TIPO_REND SEPARATED BY SPACE.
ENDCASE.






